int LED2= 13;
int LED3= 12;
int LED4= 11;
int LED5= 10;
int LED6= 9;
int LED7= 8;
int LED8= 7;
int LED9= 6;
int LED10= 5;
int LED11= 4;
int LED12= 3;
int LED13= 2;
void setup() {
  pinMode(LED2, OUTPUT);
  pinMode(LED3, OUTPUT);
  pinMode(LED4, OUTPUT);
  pinMode(LED5, OUTPUT);
  pinMode(LED6, OUTPUT);
  pinMode(LED7, OUTPUT);
  pinMode(LED8, OUTPUT); 
  pinMode(LED9, OUTPUT);
  pinMode(LED10, OUTPUT);
  pinMode(LED11, OUTPUT);
  pinMode(LED12, OUTPUT);
  pinMode(LED13, OUTPUT);
}
  void loop(){
  delay(100);
  digitalWrite(LED2, HIGH);
  delay(100);    
  digitalWrite(LED3, HIGH);
  delay(100);
  digitalWrite(LED4, HIGH);
  delay(100);    
  digitalWrite(LED5, LOW);
  delay(100);
  digitalWrite(LED6, LOW);
  delay(100);
  digitalWrite(LED7, LOW);
  delay(100);
  digitalWrite(LED8, HIGH);
  delay(100);
  digitalWrite(LED9, HIGH);
  delay(100);
  digitalWrite(LED10, HIGH);
  delay(100);
  digitalWrite(LED11, LOW);
  delay(100);
  digitalWrite(LED12, LOW);
  delay(100);
  digitalWrite(LED13, LOW);
    delay(100);
    
    
  digitalWrite(LED2, LOW); 
  delay(100);   
  digitalWrite(LED3, LOW);
  delay(100);
  digitalWrite(LED4, LOW);
  delay(100);    
  digitalWrite(LED5, HIGH);
  delay(100);
  digitalWrite(LED6, HIGH);
  delay(100);
  digitalWrite(LED7, HIGH);
  delay(100);
  digitalWrite(LED8, LOW);
  delay(100);
  digitalWrite(LED9, LOW);
  delay(100);
  digitalWrite(LED10, LOW);
  delay(100);
  digitalWrite(LED11, HIGH);
  delay(100);
  digitalWrite(LED12, HIGH);
  delay(100);
  digitalWrite(LED13, HIGH);

  
    delay(100);
  digitalWrite(LED2, HIGH);
  delay(100);    
  digitalWrite(LED3, HIGH);
  delay(100);
  digitalWrite(LED4, HIGH);
  delay(100);    
  digitalWrite(LED5, HIGH);
  delay(100);
  digitalWrite(LED6, HIGH);
  delay(100);
  digitalWrite(LED7, HIGH);
  delay(100);
  digitalWrite(LED8, HIGH);
  delay(100);
  digitalWrite(LED9, HIGH);
  delay(100);
  digitalWrite(LED10, HIGH);
  delay(100);
  digitalWrite(LED11, HIGH);
  delay(100);
  digitalWrite(LED12, HIGH);
  delay(100);
  digitalWrite(LED13, HIGH);

  
    delay(100);
  digitalWrite(LED2, LOW);
  delay(100);    
  digitalWrite(LED3, LOW);
  delay(100);
  digitalWrite(LED4, HIGH);
  delay(100);    
  digitalWrite(LED5, HIGH);
  delay(100);
  digitalWrite(LED6, HIGH);
  delay(100);
  digitalWrite(LED7, HIGH);
  delay(100);
  digitalWrite(LED8, HIGH);
  delay(100);
  digitalWrite(LED9, HIGH);
  delay(100);
  digitalWrite(LED10, HIGH);
  delay(100);
  digitalWrite(LED11, HIGH);
  delay(100);
  digitalWrite(LED12, HIGH);
  delay(100);
  digitalWrite(LED13, HIGH);

  
    delay(100);
  digitalWrite(LED2, HIGH);
  delay(100);    
  digitalWrite(LED3, LOW);
  delay(100);
  digitalWrite(LED4, LOW);
  delay(100);    
  digitalWrite(LED5, HIGH);
  delay(100);
  digitalWrite(LED6, HIGH);
  delay(100);
  digitalWrite(LED7, HIGH);
  delay(100);
  digitalWrite(LED8, HIGH);
  delay(100);
  digitalWrite(LED9, HIGH);
  delay(100);
  digitalWrite(LED10, HIGH);
  delay(100);
  digitalWrite(LED11, HIGH);
  delay(100);
  digitalWrite(LED12, HIGH);
  delay(100);
  digitalWrite(LED13, HIGH);

  
    delay(100);
  digitalWrite(LED2, HIGH);
  delay(100);    
  digitalWrite(LED3, HIGH);
  delay(100);
  digitalWrite(LED4, LOW);
  delay(100);    
  digitalWrite(LED5, LOW);
  delay(100);
  digitalWrite(LED6, HIGH);
  delay(100);
  digitalWrite(LED7, HIGH);
  delay(100);
  digitalWrite(LED8, HIGH);
  delay(100);
  digitalWrite(LED9, HIGH);
  delay(100);
  digitalWrite(LED10, HIGH);
  delay(100);
  digitalWrite(LED11, HIGH);
  delay(100);
  digitalWrite(LED12, HIGH);
  delay(100);
  digitalWrite(LED13, HIGH);

  
    delay(100);
  digitalWrite(LED2, HIGH);
  delay(100);    
  digitalWrite(LED3, HIGH);
  delay(100);
  digitalWrite(LED4, HIGH);
  delay(100);    
  digitalWrite(LED5, LOW);
  delay(100);
  digitalWrite(LED6, LOW);
  delay(100);
  digitalWrite(LED7, HIGH);
  delay(100);
  digitalWrite(LED8, HIGH);
  delay(100);
  digitalWrite(LED9, HIGH);
  delay(100);
  digitalWrite(LED10, HIGH);
  delay(100);
  digitalWrite(LED11, HIGH);
  delay(100);
  digitalWrite(LED12, HIGH);
  delay(100);
  digitalWrite(LED13, HIGH);

  
    delay(100);
  digitalWrite(LED2, HIGH);
  delay(100);    
  digitalWrite(LED3, HIGH);
  delay(100);
  digitalWrite(LED4, HIGH);
  delay(100);    
  digitalWrite(LED5, HIGH);
  delay(100);
  digitalWrite(LED6, LOW);
  delay(100);
  digitalWrite(LED7, LOW);
  delay(100);
  digitalWrite(LED8, HIGH);
  delay(100);
  digitalWrite(LED9, HIGH);
  delay(100);
  digitalWrite(LED10, HIGH);
  delay(100);
  digitalWrite(LED11, HIGH);
  delay(100);
  digitalWrite(LED12, HIGH);
  delay(100);
  digitalWrite(LED13, HIGH);

  
    delay(100);
  digitalWrite(LED2, HIGH);
  delay(100);    
  digitalWrite(LED3, HIGH);
  delay(100);
  digitalWrite(LED4, HIGH);
  delay(100);    
  digitalWrite(LED5, HIGH);
  delay(100);
  digitalWrite(LED6, HIGH);
  delay(100);
  digitalWrite(LED7, LOW);
  delay(100);
  digitalWrite(LED8, LOW);
  delay(100);
  digitalWrite(LED9, HIGH);
  delay(100);
  digitalWrite(LED10, HIGH);
  delay(100);
  digitalWrite(LED11, HIGH);
  delay(100);
  digitalWrite(LED12, HIGH);
  delay(100);
  digitalWrite(LED13, HIGH);

  
    delay(100);
  digitalWrite(LED2, HIGH);
  delay(100);    
  digitalWrite(LED3, HIGH);
  delay(100);
  digitalWrite(LED4, HIGH);
  delay(100);    
  digitalWrite(LED5, HIGH);
  delay(100);
  digitalWrite(LED6, HIGH);
  delay(100);
  digitalWrite(LED7, HIGH);
  delay(100);
  digitalWrite(LED8, LOW);
  delay(100);
  digitalWrite(LED9, LOW);
  delay(100);
  digitalWrite(LED10, HIGH);
  delay(100);
  digitalWrite(LED11, HIGH);
  delay(100);
  digitalWrite(LED12, HIGH);
  delay(100);
  digitalWrite(LED13, HIGH);

  
    delay(100);
  digitalWrite(LED2, HIGH);
  delay(100);    
  digitalWrite(LED3, HIGH);
  delay(100);
  digitalWrite(LED4, HIGH); 
  delay(100);   
  digitalWrite(LED5, HIGH);
  delay(100);
  digitalWrite(LED6, HIGH);
  delay(100);
  digitalWrite(LED7, HIGH);
  delay(100);
  digitalWrite(LED8, HIGH);
  delay(100);
  digitalWrite(LED9, LOW);
  delay(100);
  digitalWrite(LED10, LOW);
  delay(100);
  digitalWrite(LED11, HIGH);
  delay(100);
  digitalWrite(LED12, HIGH);
  delay(100);
  digitalWrite(LED13, HIGH);

  
    delay(100);
  digitalWrite(LED2, HIGH);
  delay(100);    
  digitalWrite(LED3, HIGH);
  delay(100);
  digitalWrite(LED4, HIGH);
  delay(100);    
  digitalWrite(LED5, HIGH);
  delay(100);
  digitalWrite(LED6, HIGH);
  delay(100);
  digitalWrite(LED7, HIGH);
  delay(100);
  digitalWrite(LED8, HIGH);
  delay(100);
  digitalWrite(LED9, HIGH);
  delay(100);
  digitalWrite(LED10, LOW);
  delay(100);
  digitalWrite(LED11, LOW);
  delay(100);
  digitalWrite(LED12, HIGH);
  delay(100);
  digitalWrite(LED13, HIGH);

  
    delay(100);
  digitalWrite(LED2, HIGH);
  delay(100);    
  digitalWrite(LED3, HIGH);
  delay(100);
  digitalWrite(LED4, HIGH);
  delay(100);    
  digitalWrite(LED5, HIGH);
  delay(100);
  digitalWrite(LED6, HIGH);
  delay(100);
  digitalWrite(LED7, HIGH);
  delay(100);
  digitalWrite(LED8, HIGH);
  delay(100);
  digitalWrite(LED9, HIGH);
  delay(100);
  digitalWrite(LED10, HIGH);
  delay(100);
  digitalWrite(LED11, LOW);
  delay(100);
  digitalWrite(LED12, LOW);
  delay(100);
  digitalWrite(LED13, HIGH);

  
    delay(100);
  digitalWrite(LED2, HIGH);
  delay(100);    
  digitalWrite(LED3, HIGH);
  delay(100);
  digitalWrite(LED4, HIGH);
  delay(100);    
  digitalWrite(LED5, HIGH);
  delay(100);
  digitalWrite(LED6, HIGH);
  delay(100);
  digitalWrite(LED7, HIGH);
  delay(100);
  digitalWrite(LED8, HIGH);
  delay(100);
  digitalWrite(LED9, HIGH);
  delay(100);
  digitalWrite(LED10, HIGH);
  delay(100);
  digitalWrite(LED11, HIGH);
  delay(100);
  digitalWrite(LED12, LOW);
  delay(100);
  digitalWrite(LED13, LOW);

  
    delay(100);
  digitalWrite(LED2, HIGH);
  delay(100);    
  digitalWrite(LED3, LOW);
  delay(100);
  digitalWrite(LED4, LOW);
  delay(100);    
  digitalWrite(LED5, LOW);
  delay(100);
  digitalWrite(LED6, LOW);
  delay(100);
  digitalWrite(LED7, LOW);
  delay(100);
  digitalWrite(LED8, LOW);
  delay(100);
  digitalWrite(LED9, LOW);
  delay(100);
  digitalWrite(LED10, LOW);
  delay(100);
  digitalWrite(LED11, LOW);
  delay(100);
  digitalWrite(LED12, LOW);
  delay(100);
  digitalWrite(LED13, HIGH);

 
    delay(100);
  digitalWrite(LED2, HIGH);
  delay(100);    
  digitalWrite(LED3, HIGH);
  delay(100);
  digitalWrite(LED4, LOW);
  delay(100);    
  digitalWrite(LED5, LOW);
  delay(100);
  digitalWrite(LED6, LOW);
  delay(100);
  digitalWrite(LED7, LOW);
  delay(100);
  digitalWrite(LED8, LOW);
  delay(100);
  digitalWrite(LED9, LOW);
  delay(100);
  digitalWrite(LED10, LOW);
  delay(100);
  digitalWrite(LED11, LOW);
  delay(100);
  digitalWrite(LED12, HIGH);
  delay(100);
  digitalWrite(LED13, HIGH);

  
    delay(100);
  digitalWrite(LED2, HIGH);
  delay(100);    
  digitalWrite(LED3, HIGH);
  delay(100);
  digitalWrite(LED4, HIGH); 
  delay(100);   
  digitalWrite(LED5, LOW);
  delay(100);
  digitalWrite(LED6, LOW);
  delay(100);
  digitalWrite(LED7, LOW);
  delay(100);
  digitalWrite(LED8, LOW);
  delay(100);
  digitalWrite(LED9, LOW);
  delay(100);
  digitalWrite(LED10, LOW);
  delay(100);
  digitalWrite(LED11, HIGH);
  delay(100);
  digitalWrite(LED12, HIGH);
  delay(100);
  digitalWrite(LED13, HIGH);

  
    delay(100);
  digitalWrite(LED2, HIGH);
  delay(100);    
  digitalWrite(LED3, HIGH);
  delay(100);
  digitalWrite(LED4, HIGH);
  delay(100);    
  digitalWrite(LED5, HIGH);
  delay(100);
  digitalWrite(LED6, LOW);
  delay(100);
  digitalWrite(LED7, LOW);
  delay(100);
  digitalWrite(LED8, LOW);
  delay(100);
  digitalWrite(LED9, LOW);
  delay(100);
  digitalWrite(LED10, HIGH);
  delay(100);
  digitalWrite(LED11, HIGH);
  delay(100);
  digitalWrite(LED12, HIGH);
  delay(100);
  digitalWrite(LED13, HIGH);

  
    delay(100);
  digitalWrite(LED2, HIGH);
  delay(100);    
  digitalWrite(LED3, HIGH);
  delay(100);
  digitalWrite(LED4, HIGH);
  delay(100);    
  digitalWrite(LED5, HIGH);
  delay(100);
  digitalWrite(LED6, HIGH);
  delay(100);
  digitalWrite(LED7, LOW);
  delay(100);
  digitalWrite(LED8, LOW);
  delay(100);
  digitalWrite(LED9, HIGH);
  delay(100);
  digitalWrite(LED10, HIGH);
  delay(100);
  digitalWrite(LED11, HIGH);
  delay(100);
  digitalWrite(LED12, HIGH);
  delay(100);
  digitalWrite(LED13, HIGH);

  
    delay(100);
  digitalWrite(LED2, HIGH); 
  delay(100);   
  digitalWrite(LED3, HIGH);
  delay(100);
  digitalWrite(LED4, HIGH);
  delay(100);    
  digitalWrite(LED5, HIGH);
  delay(100);
  digitalWrite(LED6, HIGH);
  delay(100);
  digitalWrite(LED7, HIGH);
  delay(100);
  digitalWrite(LED8, HIGH);
  delay(100);
  digitalWrite(LED9, HIGH);
  delay(100);
  digitalWrite(LED10, HIGH);
  delay(100);
  digitalWrite(LED11, HIGH);
  delay(100);
  digitalWrite(LED12, HIGH);
  delay(100);
  digitalWrite(LED13, HIGH);

  
  }
